# Generated by Django 3.2.7 on 2021-09-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuridModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('ayah', models.CharField(max_length=50)),
                ('ibu', models.CharField(blank=True, max_length=50)),
                ('foto', models.FileField(blank=True, upload_to='data/%Y/%m/%d')),
                ('alamat', models.TextField(blank=True)),
                ('kelahiran', models.DateField(blank=True)),
            ],
        ),
    ]
