# Generated by Django 3.2.7 on 2021-09-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_muridmodel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muridmodel',
            name='kelahiran',
            field=models.DateField(verbose_name=True),
        ),
    ]
