# Generated by Django 3.2.7 on 2021-09-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_muridmodel_kelahiran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muridmodel',
            name='kelahiran',
            field=models.DateField(blank=True, null=True),
        ),
    ]
